---
 - name: install tools
   apt: name=python-mysqldb state=present update_cache=yes
    
 - name: install mysql-server
   apt: name=mysql-server state=present update_cache=yes
    
 - name: ensure mysql-server is up and running
   service: name=mysql state=started enabled=yes

 - name: ensure mysql-server listening on all ports
   lineinfile: dest=/etc/mysql/my.cnf regexp=^bind-address line="bind-address = {{ansible_eth0.ipv4.address}}"
   notify: restart mysql-server

 - name: create demo database
   mysql_db: name={{db_name}} state=present
    
 - name: create user database
   mysql_user: name={{db_user_name}} password={{db_user_password}} priv=demo.*:ALL host='%' state=present
...

# tasks file for mysql-server